name: Upload to course
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  update_course_content:
    name: Upload files to the course
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - name: Upload to Course
        uses: Brightspace/update-course-action@master
        with:
          valenceAppId: ${{ secrets.VALENCE_APPID_PROD }}
          valenceAppKey: ${{ secrets.VALENCE_APPKEY_PROD }}
          valenceUserId: ${{ secrets.VALENCE_USERID_PROD }}
          valenceUserKey: ${{ secrets.VALENCE_USERKEY_PROD }}
          instanceDomain: universityofmanitoba.desire2learn.com
          courseOrgUnitId: 474692
          contentDirectory: content
          manifestPath: manifest.json
          dryRun: ${{ github.ref != 'refs/heads/main' }}
